services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 5s


  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - 8000:8000
    restart: always