services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}


  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000




